import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { cn } from "@/lib/utils"
import { Toaster } from "@/components/ui/sonner"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className="scrollbar-track-secondary scrollbar-thumb-muted-foreground"
    >
      <body
        className={cn(
          inter.className,
          "bg-secondary min-h-screen flex flex-col"
        )}
      >
        <Toaster position="bottom-center" />
        {children}
      </body>
    </html>
  )
}
